# Azure DevOps CI/CD Pipeline for DevOps E-Learning Platform
# Builds, tests, and deploys to Azure Container Apps

trigger:
- main

variables:
  NODE_ENV: 'production'
  REACT_APP_API_URL: 'https://your-backend-url'
  # DATABASE_URL, JWT_SECRET, etc. should be set as pipeline secrets or in variable groups

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildFrontend
        displayName: 'Build Frontend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          - script: |
              cd client
              npm install
              npm run build
            displayName: 'Build Frontend'
            env:
              REACT_APP_API_URL: $(REACT_APP_API_URL)
              NODE_ENV: $(NODE_ENV)
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'client/build'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
              replaceExistingArchive: true
            displayName: 'Archive Frontend Build'

      - job: BuildBackend
        displayName: 'Build Backend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          - script: |
              cd server
              npm install
              npm run build
            displayName: 'Build Backend'
            env:
              NODE_ENV: $(NODE_ENV)
              # DATABASE_URL: $(DATABASE_URL)
              # JWT_SECRET: $(JWT_SECRET)
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'server/dist'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
              replaceExistingArchive: true
            displayName: 'Archive Backend Build'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - deployment: DeployFrontend
        displayName: 'Deploy Frontend to Azure Web App'
        environment: 'production'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'AzureServiceConnection'
                    appType: 'webApp'
                    appName: '<YOUR_AZURE_WEBAPP_NAME>'
                    package: '$(Pipeline.Workspace)/drop/frontend.zip'
                  displayName: 'Deploy Frontend to Azure Web App'

      # Uncomment and configure the following for backend deployment
      # - deployment: DeployBackend
      #   displayName: 'Deploy Backend to Azure Web App'
      #   environment: 'production'
      #   pool:
      #     vmImage: 'ubuntu-latest'
      #   strategy:
      #     runOnce:
      #       deploy:
      #         steps:
      #           - task: DownloadBuildArtifacts@0
      #             inputs:
      #               buildType: 'current'
      #               downloadType: 'single'
      #               artifactName: 'drop'
      #           - task: AzureWebApp@1
      #             inputs:
      #               azureSubscription: 'AzureServiceConnection'
      #               appType: 'webApp'
      #               appName: '<YOUR_AZURE_BACKEND_WEBAPP_NAME>'
      #               package: '$(Pipeline.Workspace)/drop/backend.zip'
      #             displayName: 'Deploy Backend to Azure Web App'