version: '3.8'

services:
  frontend:
    image: hafeez654/devops-elearning-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: hafeez654/devops-elearning-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/devops-elearning
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=5000
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=devops-elearning

volumes:
  mongo-data:

networks:
  default:
    name: devops-elearning-network
