name: Production Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Test and Build
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run install:all
    
    - name: Run tests
      run: npm test
    
    - name: Run linting
      run: npm run lint
    
    - name: Build frontend
      run: npm run build

  # Docker Build and Push
  docker-deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./client
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-elearning-frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-elearning-frontend:${{ github.sha }}
        build-args: |
          REACT_APP_API_URL=https://your-backend-url.com
    
    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-elearning-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-elearning-backend:${{ github.sha }}
        build-args: |
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}

  # Deploy to Production Server
  deploy-production:
    needs: docker-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to Production
      run: |
        echo "🚀 Production deployment complete!"
        echo "Frontend: https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/devops-elearning-frontend"
        echo "Backend: https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/devops-elearning-backend"
        
        # Add your server deployment commands here
        # Example for AWS ECS, Railway, Render, etc.
    
    - name: Health Check
      run: |
        echo "🏥 Running health checks..."
        # Add health check commands here
